name = "BrainRegistry"
uuid = "90d52e2e-34ae-458a-9ac5-c0a9c41d363a"
repo = "https://github.com/gfayebedrin/BrainRegistry.jl"

[packages]
510a6afa-0cce-43b2-a064-ef42a99433c5 = { name = "StackedRBMs", path = "S/StackedRBMs" }
839e1aa6-2547-4afa-a76a-d5481123c40a = { name = "BrainRBM", path = "B/BrainRBM" }
9ad7a2e2-e94d-414e-b0fb-bae07cc55f5f = { name = "BrainGraph", path = "B/BrainGraph" }
